version: '3.0'
########## SERVICES ########
services:
#
###### ELASTICSEARCH
### http://elasticsearch:9200
    elasticsearch:
      image: extremeshok/elasticsearch-elasticpress:latest
      volumes:
        - vol-elasticsearch:/usr/share/elasticsearch/data
      restart: always
      labels:
        - com.centurylinklabs.watchtower.enable=true
      environment:
        - TZ=${TZ}
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      #ports:
      #  - 9200:9200
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      sysctls:
        - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
      networks:
        network:
          ipv4_address: ${IPV4_NETWORK:-172.22.1}.231